version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - MOODLE_WEB_URL=http://host.docker.internal/webservice/rest/server.php
      - MOODLE_TOKEN=709c70e9a44fdbae88555c353715581f
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VHOST=/
      - RABBITMQ_EXCHANGE_DEFAULT=default_exchange
      - RABBITMQ_EXCHANGE_TASK_SUBMIT=taskEvents
    depends_on:
      - rabbitmq
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    networks:
      - backend

networks:
  backend: